# Generated by Django 3.1.5 on 2021-09-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210920_1020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='money',
        ),
    ]
