# Generated by Django 3.1.5 on 2021-09-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default='white.png', upload_to='imgs'),
        ),
    ]
